### ISSUE TITLE
lambda only, no api

### ISSUE THREAD

**Issue by MikeBadescu** [numeract/aws-lambda-r#11]
### Problem
- not everybody wants to use API Gateway; lambda is sufficient

### TODO
- [ ] split Lambda and API script into two
- [ ] option in settings to (or not to) continue with API Gateway setup
- [ ] test of lambda function from AWS CLI
