### ISSUE TITLE
setup lambda / api scripts

### ISSUE THREAD

**Issue by MikeBadescu** [numeract/aws-lambda-r#12]
### Problem
- the scripts rely on certain AWS roles, lambda authentication function etc (one time setup) 

### TODO
- [x] decide what to automate
  + e.g., no need to create VPC and subnet --> write instructions
- [x] one-time scripts to create roles (everything related to IAM)
  + instructions / doc / script how to remove
- [x] one-time scripts to setup lambda
  + instructions / doc / script how to remove
- [x] one-time scripts to setup API gateway
  + instructions / doc / script how to remove
