### ISSUE TITLE
detailed documentation

### ISSUE THREAD

**Issue by MikeBadescu** [numeract/aws-lambda-r#14]
### Problem
- documentation is not complete, there is setup taking place outside scripts

### TODO
- [x] Instructions for each secret
  + 2-3 lines explaining where to find the info/value, similar to code comments
  + 1 (max 2) screenshots to help visualize the issue
- [x] Instructions for what is not in script
  + big picture first 
  + most important: do not forget to include any major configuration areas
- [x] instructions to terminate VMs using AWS web console
