### ISSUE TITLE
AMI management

### ISSUE THREAD

**Issue by MikeBadescu** [numeract/aws-lambda-r#3]
### Problem: 
- lambda deployment too slow

### Solution:
- use 2 AMI: amazon & project

### TODO:
- [ ] new feature branch
- [ ] in default settings, use 2 variabiles
  + `ALX_AMI_ID="ami-657bd20a"` : last version of Amazon Linux, w/o updates
  + `EC2_AMI_ID=""` 
- [ ] if `EC2_AMI_ID` not defined or there is no AMI with this ID --> 
  + check if there is a file `settings/settings_ami.txt` and whether it contains a string --> EC2_AMI_ID=string
  + again, if `EC2_AMI_ID` not defined or there is no AMI with this ID --> EC2_AMI_ID=""
- [ ] if `EC2_AMI_ID` is defined --> done, skip the steps below
- [ ] consider options not to update with yum or update R packages
- [ ] a script based on scripts 11 and 13:
  + if ALX_AMI_ID definit but no AMI  --> exit 1
  + start with ALX_AMI_ID + update + yum install + virtualenv + pip + cp + cp + install R packages + cp 
  + use $PRJ_NAME
  + do not copy files from project; do not create zip
  + create an AMI from this instance
  + write AMI ID in file  `settings/settings_ami.txt` 
  + terminate this EC2
- [ ] main script: check if file exists `settings/settings_ami.txt` and if it contains a string --> EC2_AMI_ID=string
  + if EC2_AMI_ID not defined or no AMI --> exit 1
- [ ] deployment package
  + connect to EC2_AMI_ID  
  + copy files (script 06)
  + create zip
