### ISSUE TITLE
fail if yum cannot install linux packages

### ISSUE THREAD

**Issue by MikeBadescu** [numeract/aws-lambda-r#6]
### Problem:
- script continues if yum install fails
- no option in settings to specify what to install

### TODO:
- [ ] put yum packages in an array in settings
- [ ] read array, generate install commands 
  + best if we have only one yum install command
- [ ] check for errors and fail if error after install
