### ISSUE TITLE
install R packages from github

### ISSUE THREAD

**Issue by MikeBadescu** [numeract/aws-lambda-r#8]
### Problem
- we have only one list of packages to install from CRAN

### TODO
- [ ] another array option with a list of packages to install from github
  + need to use `name/repo` format
- [ ] install devtools if github array not empty
- [ ] determine size overhead due to devtools
- [ ] script to install from github
